# Numpy

* Numpy stand for numerical python
* It's a library created mainly for array
* It has an object called nd array
* it also have the object called masked array & matrices
* i has multiple functions called linear algebra, statistical operations, random simulation, matrices, fourier transform

## array

array is a data structure, what type of data structure??

array store data of the same type.

two arrays:

[1, 2, 3, 4]

[1.1, 2.2, 3.3, 4.4]

what are the differences??

* first different is their type
* second is their location
* every items have own indexes or different positions
* their location is continuous
* 




## what are teh types of arrays??

* single dimensional arrays
* multi dimensional arrays(one dimensional, two dimensional, multi dimensional(n dimensional))

## dimensions



In [2]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
a.ndim

1

In [4]:
a[2]

3

In [5]:
b = np.array([[1, 2, 3, 4, 5, 6], [1, 2, 3, 4, 5, 6]])

In [6]:
b.ndim

2

In [7]:
b

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])

In [8]:
print(b)

[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]


In [9]:
c = np.array([[[1, 2, 3, 4, 5, 6]]])

In [10]:
c.ndim

3

In [11]:
c

array([[[1, 2, 3, 4, 5, 6]]])

In [12]:
type(c)

numpy.ndarray

In [13]:
d = np.array((1, 2, 3))

In [14]:
d

array([1, 2, 3])

In [15]:
print(d)

[1 2 3]


In [16]:
type(d)

numpy.ndarray

# difference between scalar, vector, matrices and tensor

* scalar : 1,2,3 . weight , temperature etc
* one dimensional is the vector
* two dimensional is the matrix (multiple is matrices)
* greater than two dimensional is called tensor

In [17]:
scalar = np.array(1)  # this is the scalar

In [18]:
scalar.ndim

0

In [19]:
d = np.array((1, 2, 3))  # this is the vector

In [20]:
b = np.array([[1, 2, 3, 4, 5, 6], [1, 2, 3, 4, 5, 6]])  # this is the matrix

In [21]:
c = np.array([[[1, 2, 3, 4, 5, 6]]])  # this is the tensor

## numpy data types

* integer 
* float
* complex
* boolean
* string
* 

In [22]:
zero1 = np.zeros(1)

In [23]:
zero1

array([0.])

In [33]:
np.zeros((3))

array([0., 0., 0.])

In [ ]:
np.zeros((3, 3))


In [ ]:
np.zeros((3, 3, 3))


In [34]:
np.zeros((3, 3, 3, 3))

array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]])

In [35]:
np.ones((3))

array([1., 1., 1.])

In [36]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [37]:
np.ones((3, 3, 3))

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [38]:
np.ones((3, 3, 3, 3))

array([[[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]]])

In [39]:
np.empty(3)

array([0.e+000, 5.e-324, 1.e-323])

In [43]:
np.arange(-5, 6)

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5])

In [45]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [157]:
np.linspace(1, 10, 11)

array([ 1. ,  1.9,  2.8,  3.7,  4.6,  5.5,  6.4,  7.3,  8.2,  9.1, 10. ])

# python range vs numpy arange 

np.arange() produce an array a list of numbers


range produce  a list


In [158]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [160]:
np.arange(0, 10, 2)  # working like i += 2 

array([1, 3, 5, 7, 9])

## linspace 
produces values equally between two numbers


need 15 numbers between 1,5, how?

In [162]:
np.linspace(1, 5, num=15)

array([1.        , 1.28571429, 1.57142857, 1.85714286, 2.14285714,
       2.42857143, 2.71428571, 3.        , 3.28571429, 3.57142857,
       3.85714286, 4.14285714, 4.42857143, 4.71428571, 5.        ])

## reshape

create a new shape with an existing array shape. change an array shape

In [164]:
r_shape = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

In [171]:
n_r_shape = np.reshape(r_shape, newshape=(3, 4)  )

In [172]:
n_r_shape

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [174]:
n_r_shape = np.reshape(r_shape, newshape=(6,2)  )

In [175]:
n_r_shape

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [55]:
cc = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [63]:
np.reshape(cc, newshape=(11, 1))

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [74]:
arr1 = np.array([[0, 1, 2, 3, 4, 5, ], [1, 2, 3, 4, 5, 6]])
arr1.shape

(2, 6)

In [75]:
arr1.size

12

In [76]:
arr1.dtype

dtype('int64')

In [77]:
arr1.itemsize

8

In [79]:
arr2 = np.array([[[0, 1, 2, 3, 4, 5, ], [1, 2, 3, 4, 5, 6]]])
arr2.shape

(1, 2, 6)

In [80]:
arr2.size

12

In [81]:
arr2.itemsize

8

In [82]:
arr2.data

In [ ]:
# problems

1. create a one dimensional array , 5 to 21

### sorting

In [83]:
arr3 = np.array([7, 8, 4, 5, 3, 3, 4, 8, 8, 9, 4, 8, 2, 9])
np.sort(arr3)

array([2, 3, 3, 4, 4, 4, 5, 7, 8, 8, 8, 8, 9, 9])

### make two as one array

In [84]:
h1 = np.array([1, 2, 3, 4, 5])

In [85]:
h2 = np.array([1, 2, 3, 4, 5])

In [87]:
np.concatenate((h1, h2))

array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5])

In [90]:
hh1 = np.array([[1, 2, 3], [4, 5, 6]])

In [91]:
hh2 = np.array([[7, 8, 9], [10, 11, 12]])

In [92]:
np.concatenate((hh1, hh2), axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [93]:
np.concatenate((hh1, hh2), axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

### indexing and slicing

In [94]:
index1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [95]:
index1[5]

5

In [96]:
index1[-1]

10

In [97]:
index1[3:9]

array([3, 4, 5, 6, 7, 8])

In [98]:
index1[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [99]:
index1[4:]

array([ 4,  5,  6,  7,  8,  9, 10])

In [100]:
index1[:5]

array([0, 1, 2, 3, 4])

In [101]:
index1[-3:]

array([ 8,  9, 10])

In [102]:
index1[-2:1]

array([], dtype=int64)

In [103]:
index1[0:-2]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [104]:
index1[:-2]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [106]:
# [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
index1[-2:2]

array([], dtype=int64)

In [107]:
index1[-2:-9]

array([], dtype=int64)

In [108]:
index1[-9:-1]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [109]:
index1[-9:6]

array([2, 3, 4, 5])

### create an array from existing one

In [110]:
main_arr1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [113]:
main_arr1[main_arr1 < 4]

array([0, 1, 2, 3])

### even and odd number

In [115]:
main_arr1[main_arr1 % 2 == 0]

array([ 0,  2,  4,  6,  8, 10])

In [116]:
main_arr1[main_arr1 % 2]

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0])

In [117]:
main_arr1[main_arr1 % 2 == 1]

array([1, 3, 5, 7, 9])

In [120]:
main_arr1[(main_arr1 > 2) & (main_arr1 < 6)]

array([3, 4, 5])

In [121]:
main_arr1[(main_arr1 > 2) | (main_arr1 < 6)]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [123]:
(main_arr1 > 2) & (main_arr1 < 6)

array([False, False, False,  True,  True,  True, False, False, False,
       False, False])

In [127]:
np.arange(0, 25).reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [131]:
two_d_arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [5, 6, 7, 8]
])

In [133]:
two_d_arr[1][1]

6

In [136]:
two_d_arr[0:2, 1:3]

array([[2, 3],
       [6, 7]])

## 2d problems

In [138]:
two_d_arr1 = np.arange(1, 26).reshape(5, 5)

In [139]:
two_d_arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [143]:
# all the numbers in row zero

two_d_arr1[0]

array([1, 2, 3, 4, 5])

In [145]:
two_d_arr1[:, 2:3]

array([[ 3],
       [ 8],
       [13],
       [18],
       [23]])

In [146]:
# all the numbers between 16 to 18

In [148]:
two_d_arr1[3][0:3]

array([16, 17, 18])

In [149]:
print(two_d_arr1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [150]:
two_d_arr1[3:, :3]

array([[16, 17, 18],
       [21, 22, 23]])

In [151]:
two_d_arr1[2][[2]]

array([13])

In [152]:
two_d_arr1[1:3, :]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [153]:
print(two_d_arr1)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [155]:
two_d_arr1[:, 1:3]

array([[ 2,  3],
       [ 7,  8],
       [12, 13],
       [17, 18],
       [22, 23]])